name: zed_store_mangent
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^2.0.1
  introduction_screen: ^4.0.0
  google_fonts: ^8.0.2
  flutter_screenutil: ^5.9.3
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.5
  pretty_dio_logger: ^1.4.0
  cached_network_image: ^3.4.1
  auto_route: ^11.1.0
  injectable: ^2.7.1+4
  googleapis_auth: ^2.0.0
  get_it: ^9.2.1
  mobile_scanner: ^5.1.0
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  fl_chart: ^0.68.0
  cloud_firestore: ^6.1.2
  build_runner: ^2.13.1
  dio: ^5.9.2
  shimmer: ^3.0.0
  equatable: ^2.0.8
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  app_links: ^6.3.2
  dartz: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  qr_flutter: ^4.1.0
  google_generative_ai: ^0.4.5
  connectivity_plus: ^7.1.1
  flutter_native_splash: ^2.4.7
  lottie: ^3.3.3
  flutter_dotenv: ^5.1.0
  permission_handler: ^11.3.1
  vibration: ^3.1.8
  firebase_messaging: ^16.2.0
  flutter_local_notifications: ^21.0.0
  bloc_concurrency: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.5.0
  injectable_generator: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/zid-manager-e61b2-firebase-adminsdk-fbsvc-be65e148f3.json
    - .env.example
# إعدادات أيقونات التطبيق (تأكد من وجود الصورة في المسار الصحيح)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/lanucher.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/lanucher.png"